data:extend({{
    type = "item",
    name = "simple-logistic-chest-passive-provider",
    icon = "__botsbotsbots-fast__/graphics/icons/logistic-chest-passive-provider.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "container-0",
    order = "b[storage]-0-a[logistic-chest-passive-provider]",
    place_result = "simple-logistic-chest-passive-provider",
    stack_size = 50,
}, {
    type = "item",
    name = "simple-logistic-chest-active-provider",
    icon = "__botsbotsbots-fast__/graphics/icons/logistic-chest-active-provider.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "container-0",
    order = "b[storage]-0-b[logistic-chest-active-provider]",
    place_result = "simple-logistic-chest-active-provider",
    stack_size = 50,
}, {
    type = "item",
    name = "simple-logistic-chest-storage",
    icon = "__botsbotsbots-fast__/graphics/icons/logistic-chest-storage.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "container-0",
    order = "b[storage]-0-c[logistic-chest-storage]",
    place_result = "simple-logistic-chest-storage",
    stack_size = 50,
}, {
    type = "item",
    name = "simple-logistic-chest-buffer",
    icon = "__botsbotsbots-fast__/graphics/icons/logistic-chest-buffer.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "container-0",
    order = "b[storage]-0-d[logistic-chest-buffer]",
    place_result = "simple-logistic-chest-buffer",
    stack_size = 50,
}, {
    type = "item",
    name = "simple-logistic-chest-requester",
    icon = "__botsbotsbots-fast__/graphics/icons/logistic-chest-requester.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "container-0",
    order = "b[storage]-0-e[logistic-chest-requester]",
    place_result = "simple-logistic-chest-requester",
    stack_size = 50,
}})
